<?php 	include_once( "test.lib.php" ); ?>
<html>
<head>
	<title>PHP FormMail Generator - A tool to create ready-to-use web forms in a flash | Demo Template</title>
<!-- 	
	<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1">
 -->
	<meta name="keywords" content="PHP FormMail Generator, phpFormMailGen, Customize Forms, phpFormMailGenerator,formmail.php, formmail.pl, formMail Generator, PHP, Generator, Backend Tool, phpFormGen, phpFormGenerator, anti-spam, web hosting">
	<meta name="description" content="PHP formMail Generator - A tool to ceate ready-to-use web forms in a flash">
 	<style type='text/css'>
		.form_title{
			color : #000000;
			font-size: 13px;
			font-family: verdana, Geneva, Arial, Helvetica, sans-serif;
			font-weight : bold;
		}
		
		.form_field {
			font-size : 13px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #474747;
			font-weight : bold;
			text-align:left;
		}
		
		.form_text{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
		}
		
		.text_box{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
			width:200px;
		}
		
		.text_area{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
			width:200px;
			height:60px;
		}
		
		.text_select{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
		}

		.form_error{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #ff0000;
			font-weight : bold;
		}

		.copyright{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
		}
		
	</style>
</head>

<body  marginheight="0" marginwidth="0" leftmargin="0" topmargin="0">




<meta http-equiv="content-type" content="text/html; charset=">


<!-- ------------------------ Begin: Your FormMail's Description  ------------------------ -->

<br><br><br>
<table cellspacing='16' cellpadding='0' border='0' align='center' ><tr><td>

<b>PHP FormMail Generator</b> - A tool to ceate ready-to-use web forms in a flash. 
Once the form has been generated, you have a full functional web form.
Including error checking of required fields, email address validation, credit card number & expirey date.
checking, multiple attchments sending, email auto responding.

<br><br><br>
<b>Features :</b>
 <br><br>
<blockquote>
	<li type="square"></li>Unlimited fields of form
	<li type="square"></li>All standard type of fields, plus lots of template, such as credit card number & expirey date...  
	<li type="square"></li>List/menu builder for multiple lists of Radio Buttons, Selection Menu, Check Box.
	<li type="square"></li>Error checking : credit card number & expirey date, email address, required fields checking. 
	<li type="square"></li>Mail multiple attachments
	<li type="square"></li>Email auto responding
	<li type="square"></li>Store submited form data to a text file
	<li type="square"></li>Multiple language support ( to do )
	<li type="square"></li>Anti-spam feature for ISP companys( to do )
</blockquote>

</td></tr></table>

<!-- ------------------------ End: Your FormMail's Description  ------------------------ -->





<!-- =======================  Begin: Form Generated By PHP FormMail Generator ======================= -->



<?php
	if( !$isHideForm ): 
		global $sErr ;
		if( $sErr ) print "<br><a name='error'></a><center><font class='form_error' >$sErr</font></center><br>"; 

		$starColor = $sErr ? "#ff0000" : "#000000";
		$style=" class='form_text' ";
 ?>

<form name="frmFormMail" action="<?php print PHP_SELF ?>" method='post' enctype='multipart/form-data'>
<input type='hidden' name='formmail_submit' value='Y'>
<input type='hidden' name='esh_formmail_recipient' value="s6software@users.sourceforge.net">
<input type='hidden' name='esh_formmail_subject' value="Testing All Data Type of PHP FormMail Generator V1.0">
<input type='hidden' name='esh_formmail_cc' value="">
<input type='hidden' name='esh_formmail_bcc' value="">
<input type='hidden' name='esh_formmail_return_subject' value="Subject of Mail Auto Response Message">
<input type='hidden' name='esh_formmail_return_msg' value="Dear Tester:

Thank you for testing PHP FormMail Generator.


PHP FormMail Generator - A tool to ceate ready-to-use web forms in a flash. Once the form has been generated, you have a full functional web form. Including error checking of required fields, email address validation, credit card number &amp; expirey date. checking, multiple attchments sending, email auto responding. 


Features : 


Unlimited fields of form 
All standard type of fields, plus lots of template, such as credit card number &amp; expirey date... 
List/menu builder for multiple lists of Radio Buttons, Selection Menu, Check Box. 
Error checking : credit card number &amp; expirey date, email address, required fields checking. 
Mail multiple attachments 
Email auto responding 
Store submited form data to a text file 
Multiple language support ( to do ) 
Anti-spam feature for ISP companys( to do ) 

">
<input type='hidden' name='esh_formmail_mail_and_file' value="">
<input type='hidden' name='esh_formmail_charset' value="">

<table cellspacing='16' cellpadding='0' border='0'  >
	<tr>
		<td class="form_field" valign='top' align='right'>Sender's E-mail </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="sender's email" name="Sender_E-mail"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Sender_E-mail" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Generic E-mail </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="generic email" name="Generic_E-mail"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Generic_E-mail" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Special Text( ,./&lt;&gt;?;:'&quot;[]{}\|`~!@#$%^&amp;*()_+=-) </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<input type="text" name="Special_Text"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Special_Text" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Radio </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="radio" name="Radio"  value="Google.com"  <?php  formChecked( $HTTP_POST_VARS[ "Radio" ], "Google.com" ); ?> > Google.com<br>
<input type="radio" name="Radio"  value="PHP.Net"  <?php  formChecked( $HTTP_POST_VARS[ "Radio" ], "PHP.Net" ); ?> > PHP.Net<br>
<input type="radio" name="Radio"  value="SourceForge.net"  <?php  formChecked( $HTTP_POST_VARS[ "Radio" ], "SourceForge.net" ); ?> > SourceForge.net<br>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>CheckBox </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="checkbox" name="Checkbox01_CheckBox"  value="Unix"  <?php  formChecked( $HTTP_POST_VARS[ "Checkbox01_CheckBox" ], "Unix" ); ?> > Unix<br>
<input type="checkbox" name="Checkbox02_CheckBox"  value="FreeBSD"  <?php  formChecked( $HTTP_POST_VARS[ "Checkbox02_CheckBox" ], "FreeBSD" ); ?> > FreeBSD<br>
<input type="checkbox" name="Checkbox03_CheckBox"  value="Linux"  <?php  formChecked( $HTTP_POST_VARS[ "Checkbox03_CheckBox" ], "Linux" ); ?> > Linux<br>
<input type="checkbox" name="Checkbox04_CheckBox"  value="Windows"  <?php  formChecked( $HTTP_POST_VARS[ "Checkbox04_CheckBox" ], "Windows" ); ?> > Windows<br>
<input type="checkbox" name="Checkbox05_CheckBox"  value="Mac"  <?php  formChecked( $HTTP_POST_VARS[ "Checkbox05_CheckBox" ], "Mac" ); ?> > Mac<br>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Select Credit Card </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<select name="Select_Credit_Card" <? print $style; ?>>
<option value=''>- Select -</option>
 <option  value="Visa"  <?php  formSelected( $HTTP_POST_VARS[ "Select_Credit_Card" ], "Visa" ); ?> > Visa
<option  value="MasterCard"  <?php  formSelected( $HTTP_POST_VARS[ "Select_Credit_Card" ], "MasterCard" ); ?> > MasterCard
<option  value="American Express"  <?php  formSelected( $HTTP_POST_VARS[ "Select_Credit_Card" ], "American Express" ); ?> > American Express
</select>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>TextArea </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<textarea name="TextArea" rows=4 cols=25 ><?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "TextArea" ] ); ?></textarea>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Attachment </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="file" name="Attachment"  value="" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Password </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<input type="password" name="Password"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Password" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Credit Card Expiry Date </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
	<?php 
selectList( "Credit_Card_Expiry_Date_MM", $HTTP_POST_VARS["Credit_Card_Expiry_Date_MM"], 1, 12, "MM", $style ) ;
selectList( "Credit_Card_Expiry_Date_YYYY", $HTTP_POST_VARS["Credit_Card_Expiry_Date_YYYY"], date("Y"), date("Y")+3, "YYYY", $style ) ;
?>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Credit Card# </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="creditcard#" maxlength=16 name="Credit_Card#"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Credit_Card#" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Generic Date Selection 1 </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<?php 
selectList( "Generic_Date_Selection_1_MM", $HTTP_POST_VARS["Generic_Date_Selection_1_MM"], 1, 12, "MM", $style ) ;
selectList( "Generic_Date_Selection_1_DD", $HTTP_POST_VARS["Generic_Date_Selection_1_DD"], 1, 31, "DD", $style ) ;
selectList( "Generic_Date_Selection_1_YYYY", $HTTP_POST_VARS["Generic_Date_Selection_1_YYYY"], date("Y"), date("Y")+3, "YYYY", $style ) ;
?>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Generic Date Selection 2 </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
	<?php 
selectList( "Generic_Date_Selection_2_MM", $HTTP_POST_VARS["Generic_Date_Selection_2_MM"], 1, 12, "MM", $style ) ;
selectList( "Generic_Date_Selection_2_YYYY", $HTTP_POST_VARS["Generic_Date_Selection_2_YYYY"], date("Y"), date("Y")+3, "YYYY", $style ) ;
?>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Generic Time Selection 1 </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<?php 
selectList( "Generic_Time_Selection_1_HH", $HTTP_POST_VARS["Generic_Time_Selection_1_HH"], 0, 23, "HH", $style ) ;
selectList( "Generic_Time_Selection_1_MM", $HTTP_POST_VARS["Generic_Time_Selection_1_MM"], 0, 59, "MM", $style ) ;
selectList( "Generic_Time_Selection_1_SS", $HTTP_POST_VARS["Generic_Time_Selection_1_SS"], 0, 59, "SS", $style ) ;
?>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Generic Time Selection 2 </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<?php 
selectList( "Generic_Time_Selection_2_HH", $HTTP_POST_VARS["Generic_Time_Selection_2_HH"], 0, 23, "HH", $style ) ;
selectList( "Generic_Time_Selection_2_MM", $HTTP_POST_VARS["Generic_Time_Selection_2_MM"], 0, 59, "MM", $style ) ;
?>

		</td>
	</tr>


	<tr><td colspan=3 align='center'><input type='submit' value='Submit'> &nbsp;&nbsp; <input type='button' value='Cancel' onclick="location.href='/';"></td></tr>
</table>


</form>




<!-- =======================  End:  ======================= -->



<?php
		if( $sErr ) print "<script language='javascript' type='text/javascript'>location.href='#error';</script>";;; 

else: //!$isHideForm
	print( "<br><br><hr><center><b>Your form has been sent. Thank you.</b><br><br><input type='button' value='Home' onclick=\"location.href='/';\"></center><br><br>" );
endif; //!$isHideForm
			?>
	<!-- -------------------------------------- COPY RIGHT -------------------------------------- -->

	<br><br><br><br>
	
	<div align="right" class='copyright'>
		<b>Generated by : </b> 
		<a href="http://phpfmg.sourceforge.net" target="_blank">phpFormMail Generator</a> V1.0 - A tool to create ready-to-use web forms in a flash! &nbsp;&nbsp;
	</div>
	<br><br><br>
 </body>
</html>