<?
	include( "include.php" );
// ==============================================	
	commonHeader( "Sample of Google" );
?>
<table cellpadding="0" cellspacing="0" border="0" width="90%" align="center">
	<tr>
		<td>

<b>Demo of form "Information Request for Search Services" in <img src="pics/logo/google.gif" border=0 alt="The Best Search Engine"></b>		
 <br><br>
<blockquote>
	This form is used for demo purpose. It's generated by PHP FormMail Generator and I didn't change any byte of coding.
	<p>
	Here are the steps I took and the results I got.
<form>
	<li type="square"></li><a href="demo.google.html" target="_blank">Use Generator like this</a><p>
	<li type="square"></li><a href="samples/20030303-2536.php" target="_blank">A generated ready-to-use web form like this</a><p>

	<li type="square"></li>A sample mail sent by the form as follow:<br>
<textarea rows="3" cols="50" wrap="off">
Company name 	 : SourceForge.Net
Contact name 	 : Raymond
Email address 	 : s6software@users.sourceforge.net
Phone number 	 : 123-4567
State 	 : California
URL of site 	 : http://phpfmg.sourceforge.net
Which Custom Search option interests you? 	 : WebSearch
Estimated number of search queries PER DAY 	 : 100,000 to 250,000
Website size (approximate # of pages) 	 : 50
When are you planning to launch a new search service on your site? 	 : 
Within the next 3 months
What type of company do you work for? (e.g. software, health, travel, 
etc.)  	 : software
How did you hear about Google? 	 : In a news article ?
Comments 	 : What a greate site!


IP:216.18.70.26


</textarea>
<p>

	<li type="square"></li>A auto responding mail I got as follow:<br>
<textarea rows="3" cols="50" wrap="off">
Dear Tester:

Thank you for your testing.

Any feed back are welcome!

Thanks again

Raymond
</textarea>	

<p>

	<li type="square"></li>A file google.txt of saved the sumitted data as follow:<br>
<textarea rows="3" cols="50" wrap="off">
<? print htmlSpecialChars( readFile2Str( "samples/google.txt") );?>
</textarea>	

	
</form>		
	<em><a href="samples/20030303-2536.php" target="_blank">You can refresh this page to see your data after you test drive the form.</a></em>
	<p>

</blockquote>

<b>Compare two forms:</b>
<blockquote>
	<li type="square"></li><a href="http://services.google.com/licensing/request" target="_blank">The real one in Google.com.</a>
	<li type="square"></li><a href="samples/20030303-2536.php" target="_blank">The one generated by PHP FormMail Generator.</a>
</blockquote>

		</td>
	</tr>
</table>
<?
	commonFooter();
// ==============================================	
?>