<?php 	include_once( "20030303-2536.lib.php" ); ?>
<html>
<head>
	<title>PHP FormMail Generator - A tool to create ready-to-use web forms in a flash | Demo Template</title>
<!-- 	
	<meta http-equiv="Content-type" content="text/html; charset=iso-8859-1">
 -->
	<meta name="keywords" content="PHP FormMail Generator, phpFormMailGen, Customize Forms, phpFormMailGenerator,formmail.php, formmail.pl, formMail Generator, PHP, Generator, Backend Tool, phpFormGen, phpFormGenerator, anti-spam, web hosting">
	<meta name="description" content="PHP formMail Generator - A tool to ceate ready-to-use web forms in a flash">
 	<style type='text/css'>
		.form_title{
			color : #000000;
			font-size: 13px;
			font-family: verdana, Geneva, Arial, Helvetica, sans-serif;
			font-weight : bold;
		}
		
		.form_field {
			font-size : 13px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #474747;
			font-weight : bold;
			text-align:left;
		}
		
		.form_text{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
		}
		
		.text_box{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
			width:200px;
		}
		
		.text_area{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
			width:200px;
			height:60px;
		}
		
		.text_select{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
		}

		.form_error{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #ff0000;
			font-weight : bold;
		}

		.copyright{
			font-size : 11px;
			font-family : Verdana, Arial, Helvetica, sans-serif;
			color : #000000;
		}
		
	</style>
</head>

<body  marginheight="0" marginwidth="0" leftmargin="0" topmargin="0">




<meta http-equiv="content-type" content="text/html; charset=">


<!-- ------------------------ Begin: Your FormMail's Description  ------------------------ -->

<br><br><br>
<table cellspacing='16' cellpadding='0' border='0' align='center' ><tr><td>

<font face="arial, sans-serif" size=3 color='red'><b>Warning:</b> This is a DEMO purpose form. All the email will NOT send to Google.
<a href="http://services.google.com/licensing/request" target="_blank">Click to Google real form</a>.
</font>
<p>

<table width="90%" border=0 cellpadding=2 cellspacing=0>
  <tr valign="top"> 
    <td width="1%"> <img src="http://services.google.com/images/google_sm.gif" border=0
             width="143" height="59" alt="Google" align="left" vspace="10"> 
    </td>
    <td width="99%" bgcolor="#ffffff" valign="middle"> 
      <table width="100%" cellpadding="3">
        <tr bgcolor="ddad08"> 
          <td><b><font color="#FFFFFF" face="Arial, sans-serif">&nbsp;For&nbsp;Site&nbsp;Owners:&nbsp;Search&nbsp;Services 
            </font></b></td>
          </tr>
        </table>
     </td></tr>
</table>


<font face="arial, sans-serif"><b>Information Request for Search Services</b></font> 
<P>Thanks for considering Google for providing your site with search services. 
  Please take a moment to complete the form below. This information will help 
  us to tailor our response to your specific search needs. Thank you for your 
  interest in Google.</P>
<P><i><font size="-1">Required fields are bolded with <font color="#990000">*</font>.</font></i></P>

</td></tr></table>

<!-- ------------------------ End: Your FormMail's Description  ------------------------ -->





<!-- =======================  Begin: Form Generated By PHP FormMail Generator ======================= -->



<?php
	if( !$isHideForm ): 
		global $sErr ;
		if( $sErr ) print "<br><a name='error'></a><center><font class='form_error' >$sErr</font></center><br>"; 

		$starColor = $sErr ? "#ff0000" : "#000000";
		$style=" class='form_text' ";
 ?>

<form name="frmFormMail" action="<?php print PHP_SELF ?>" method='post' enctype='multipart/form-data'>
<input type='hidden' name='formmail_submit' value='Y'>
<input type='hidden' name='esh_formmail_recipient' value="s6software@users.sourceforge.net">
<input type='hidden' name='esh_formmail_subject' value="Demo Google Sign Up Search Services">
<input type='hidden' name='esh_formmail_cc' value="">
<input type='hidden' name='esh_formmail_bcc' value="">
<input type='hidden' name='esh_formmail_return_subject' value="Demo of PHP FormMail Generator">
<input type='hidden' name='esh_formmail_return_msg' value="Dear Tester:

Thank you for your testing.

Any feed back are welcome!

Thanks again

Raymond">
<input type='hidden' name='esh_formmail_mail_and_file' value="">
<input type='hidden' name='esh_formmail_charset' value="">

<table cellspacing='16' cellpadding='0' border='0'  >
	<tr>
		<td class="form_field" valign='top' align='right'>Company name </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="text" name="Company_name"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Company_name" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Contact name </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="text" name="Contact_name"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Contact_name" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Email address </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="sender's email" name="Email_address"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Email_address" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Phone number </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="text" name="Phone_number"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Phone_number" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>State </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<select name="State" <? print $style; ?>>
<option value=''>- Select -</option>
 <option  value="Not Applicable"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Not Applicable" ); ?> > Not Applicable
<option  value="Alabama"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Alabama" ); ?> > Alabama
<option  value="Alaska"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Alaska" ); ?> > Alaska
<option  value="Arizona"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Arizona" ); ?> > Arizona
<option  value="Arkansas"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Arkansas" ); ?> > Arkansas
<option  value="California"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "California" ); ?> > California
<option  value="Colorado"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Colorado" ); ?> > Colorado
<option  value="Connecticut"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Connecticut" ); ?> > Connecticut
<option  value="Delaware"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Delaware" ); ?> > Delaware
<option  value="District of Columbia"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "District of Columbia" ); ?> > District of Columbia
<option  value="Florida"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Florida" ); ?> > Florida
<option  value="Georgia"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Georgia" ); ?> > Georgia
<option  value="Hawaii"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Hawaii" ); ?> > Hawaii
<option  value="Idaho"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Idaho" ); ?> > Idaho
<option  value="Illinois"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Illinois" ); ?> > Illinois
<option  value="Indiana"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Indiana" ); ?> > Indiana
<option  value="Iowa"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Iowa" ); ?> > Iowa
<option  value="Kansas"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Kansas" ); ?> > Kansas
<option  value="Kentucky"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Kentucky" ); ?> > Kentucky
<option  value="Louisiana"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Louisiana" ); ?> > Louisiana
<option  value="Maine"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Maine" ); ?> > Maine
<option  value="Maryland"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Maryland" ); ?> > Maryland
<option  value="Massachusetts"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Massachusetts" ); ?> > Massachusetts
<option  value="Michigan"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Michigan" ); ?> > Michigan
<option  value="Minnesota"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Minnesota" ); ?> > Minnesota
<option  value="Mississippi"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Mississippi" ); ?> > Mississippi
<option  value="Missouri"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Missouri" ); ?> > Missouri
<option  value="Montana"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Montana" ); ?> > Montana
<option  value="Nebraska"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Nebraska" ); ?> > Nebraska
<option  value="Nevada"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Nevada" ); ?> > Nevada
<option  value="New Hampshire"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "New Hampshire" ); ?> > New Hampshire
<option  value="New Jersey"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "New Jersey" ); ?> > New Jersey
<option  value="New Mexico"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "New Mexico" ); ?> > New Mexico
<option  value="New York"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "New York" ); ?> > New York
<option  value="North Carolina"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "North Carolina" ); ?> > North Carolina
<option  value="North Dakota"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "North Dakota" ); ?> > North Dakota
<option  value="Ohio"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Ohio" ); ?> > Ohio
<option  value="Oklahoma"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Oklahoma" ); ?> > Oklahoma
<option  value="Oregon"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Oregon" ); ?> > Oregon
<option  value="Pennsylvania"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Pennsylvania" ); ?> > Pennsylvania
<option  value="Rhode Island"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Rhode Island" ); ?> > Rhode Island
<option  value="South Carolina"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "South Carolina" ); ?> > South Carolina
<option  value="South Dakota"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "South Dakota" ); ?> > South Dakota
<option  value="Tennessee"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Tennessee" ); ?> > Tennessee
<option  value="Texas"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Texas" ); ?> > Texas
<option  value="Utah"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Utah" ); ?> > Utah
<option  value="Vermont"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Vermont" ); ?> > Vermont
<option  value="Virginia"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Virginia" ); ?> > Virginia
<option  value="Washington"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Washington" ); ?> > Washington
<option  value="West Virginia"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "West Virginia" ); ?> > West Virginia
<option  value="Wisconsin"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Wisconsin" ); ?> > Wisconsin
<option  value="Wyoming"  <?php  formSelected( $HTTP_POST_VARS[ "State" ], "Wyoming" ); ?> > Wyoming
</select>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>URL of site </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="text" name="URL_of_site"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "URL_of_site" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Which Custom Search option interests you? </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<select name="Which_Custom_Search_option_interests_you" <? print $style; ?>>
<option value=''>- Select -</option>
 <option  value="WebSearch"  <?php  formSelected( $HTTP_POST_VARS[ "Which_Custom_Search_option_interests_you" ], "WebSearch" ); ?> > WebSearch
<option  value="SiteSearch"  <?php  formSelected( $HTTP_POST_VARS[ "Which_Custom_Search_option_interests_you" ], "SiteSearch" ); ?> > SiteSearch
<option  value="WebSearch and SiteSearch"  <?php  formSelected( $HTTP_POST_VARS[ "Which_Custom_Search_option_interests_you" ], "WebSearch and SiteSearch" ); ?> > WebSearch and SiteSearch
<option  value="Other"  <?php  formSelected( $HTTP_POST_VARS[ "Which_Custom_Search_option_interests_you" ], "Other" ); ?> > Other
</select>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Estimated number of search queries PER DAY </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<select name="Estimated_number_of_search_queries_PER_DAY" <? print $style; ?>>
<option value=''>- Select -</option>
 <option  value="less than 5,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "less than 5,000" ); ?> > less than 5,000
<option  value="5,000 - 10,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "5,000 - 10,000" ); ?> > 5,000 - 10,000
<option  value="10,000 - 25,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "10,000 - 25,000" ); ?> > 10,000 - 25,000
<option  value="25,000 - 50,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "25,000 - 50,000" ); ?> > 25,000 - 50,000
<option  value="50,000 - 100,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "50,000 - 100,000" ); ?> > 50,000 - 100,000
<option  value="100,000 to 250,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "100,000 to 250,000" ); ?> > 100,000 to 250,000
<option  value="250,000 to 500,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "250,000 to 500,000" ); ?> > 250,000 to 500,000
<option  value="500,000 to 1,000,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "500,000 to 1,000,000" ); ?> > 500,000 to 1,000,000
<option  value="more than 1,000,000"  <?php  formSelected( $HTTP_POST_VARS[ "Estimated_number_of_search_queries_PER_DAY" ], "more than 1,000,000" ); ?> > more than 1,000,000
</select>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Website size (approximate # of pages) </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<input type="text" name="Website_size_(approximate_#_of_pages)"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Website_size_(approximate_#_of_pages)" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>When are you planning to launch a new search service on your site? </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="radio" name="When_are_you_planning_to_launch_a_new_search_service_on_your"  value="Within the next month"  <?php  formChecked( $HTTP_POST_VARS[ "When_are_you_planning_to_launch_a_new_search_service_on_your" ], "Within the next month" ); ?> > Within the next month<br>
<input type="radio" name="When_are_you_planning_to_launch_a_new_search_service_on_your"  value="Within the next 3 months"  <?php  formChecked( $HTTP_POST_VARS[ "When_are_you_planning_to_launch_a_new_search_service_on_your" ], "Within the next 3 months" ); ?> > Within the next 3 months<br>
<input type="radio" name="When_are_you_planning_to_launch_a_new_search_service_on_your"  value="Within the next 6 months"  <?php  formChecked( $HTTP_POST_VARS[ "When_are_you_planning_to_launch_a_new_search_service_on_your" ], "Within the next 6 months" ); ?> > Within the next 6 months<br>
<input type="radio" name="When_are_you_planning_to_launch_a_new_search_service_on_your"  value="Within the next 12 months or more"  <?php  formChecked( $HTTP_POST_VARS[ "When_are_you_planning_to_launch_a_new_search_service_on_your" ], "Within the next 12 months or more" ); ?> > Within the next 12 months or more<br>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>What type of company do you work for? (e.g. software, health, travel, etc.)  </td><td width='10'  aligh='right' valign='top'> <font size='2' color='#ff0000'>*</font> </td>
		<td class="form_text">
<input type="text" name="What_type_of_company_do_you_work_for_(e_g_software_health_tr"  value="<?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "What_type_of_company_do_you_work_for_(e_g_software_health_tr" ] ); ?>" class='text_box'>
		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>How did you hear about Google? </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<input type="radio" name="How_did_you_hear_about_Google"  value="From a colleague or friend ?"  <?php  formChecked( $HTTP_POST_VARS[ "How_did_you_hear_about_Google" ], "From a colleague or friend ?" ); ?> > From a colleague or friend ?<br>
<input type="radio" name="How_did_you_hear_about_Google"  value="On Google.com ?"  <?php  formChecked( $HTTP_POST_VARS[ "How_did_you_hear_about_Google" ], "On Google.com ?" ); ?> > On Google.com ?<br>
<input type="radio" name="How_did_you_hear_about_Google"  value="In a news article ?"  <?php  formChecked( $HTTP_POST_VARS[ "How_did_you_hear_about_Google" ], "In a news article ?" ); ?> > In a news article ?<br>
<input type="radio" name="How_did_you_hear_about_Google"  value="From an advertisment ?"  <?php  formChecked( $HTTP_POST_VARS[ "How_did_you_hear_about_Google" ], "From an advertisment ?" ); ?> > From an advertisment ?<br>
<input type="radio" name="How_did_you_hear_about_Google"  value="Other"  <?php  formChecked( $HTTP_POST_VARS[ "How_did_you_hear_about_Google" ], "Other" ); ?> > Other<br>

		</td>
	</tr>

	<tr>
		<td class="form_field" valign='top' align='right'>Comments </td><td width='10'  aligh='right' valign='top'></td>
		<td class="form_text">
<textarea name="Comments" rows=4 cols=25 ><?php  print HtmlSpecialChars( $HTTP_POST_VARS[ "Comments" ] ); ?></textarea>

		</td>
	</tr>


	<tr><td colspan=3 align='center'><input type='submit' value='Submit'> &nbsp;&nbsp; <input type='button' value='Cancel' onclick="location.href='/';"></td></tr>
</table>


</form>




<!-- =======================  End:  ======================= -->



<?php
		if( $sErr ) print "<script language='javascript' type='text/javascript'>location.href='#error';</script>";;; 

else: //!$isHideForm
	print( "<br><br><hr><center><b>Your form has been sent. Thank you.</b><br><br><input type='button' value='Home' onclick=\"location.href='/';\"></center><br><br>" );
endif; //!$isHideForm
			?>
	<!-- -------------------------------------- COPY RIGHT -------------------------------------- -->

	<br><br><br><br>
	
	<div align="right" class='copyright'>
		<b>Generated by : </b> 
		<a href="http://phpfmg.sourceforge.net" target="_blank">phpFormMail Generator</a> V1.0 - A tool to create ready-to-use web forms in a flash! &nbsp;&nbsp;
	</div>
	<br><br><br>
 </body>
</html>